# Generated by Django 5.1.7 on 2025-04-15 04:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Dala nomi')),
                ('location', models.CharField(max_length=200, verbose_name='Manzil')),
                ('total_area', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Umumiy maydon (gektar)')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Kenglik')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Uzunlik')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dala',
                'verbose_name_plural': 'Dalalar',
            },
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Maydon nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('area', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Maydon (gektar)')),
                ('crop_type', models.CharField(max_length=100, verbose_name='Ekin turi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('yetarli', 'Yetarli'), ('ortacha', "O'rtacha"), ('sugorish_kerak', "Sug'orish kerak")], default='yetarli', max_length=40, verbose_name='Holat')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='irrigation.field')),
            ],
            options={
                'verbose_name': 'Maydon',
                'verbose_name_plural': 'Maydonlar',
            },
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nasos nomi')),
                ('is_active', models.BooleanField(default=False, verbose_name='Faol')),
                ('last_status_change', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Oxirgi holat o'zgarishi")),
                ('speed', models.PositiveSmallIntegerField(default=0, verbose_name='Tezlik (0-100)')),
                ('max_capacity', models.PositiveSmallIntegerField(default=100, verbose_name='Maksimal quvvat (l/s)')),
                ('serving_fields', models.ManyToManyField(blank=True, related_name='pumps', to='irrigation.field')),
            ],
            options={
                'verbose_name': 'Nasos',
                'verbose_name_plural': 'Nasoslar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PumpActionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('activated', 'Yoqilgan'), ('deactivated', "O'chirilgan")], max_length=20, verbose_name='Harakat')),
                ('timestamp', models.DateTimeField(verbose_name='Vaqt')),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_history', to='irrigation.pump')),
            ],
            options={
                'verbose_name': 'Nasos harakati tarixi',
                'verbose_name_plural': 'Nasos harakatlari tarixi',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('status', models.CharField(choices=[('yetarli', 'Yetarli'), ('ortacha', "O'rtacha"), ('sugorish_kerak', "Sug'orish kerak")], max_length=20, verbose_name='Holat')),
                ('moisture_level', models.FloatField(blank=True, null=True, verbose_name='Namlik darajasi')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Harorat')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='irrigation.plot')),
            ],
            options={
                'verbose_name': 'Holat tarixi',
                'verbose_name_plural': 'Holat tarixi',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('temperature', 'Harorat'), ('humidity', 'Namlik')], max_length=20, verbose_name='Sensor turi')),
                ('value', models.FloatField(verbose_name='Qiymat')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='irrigation.plot')),
            ],
            options={
                'verbose_name': "Sensor ma'lumoti",
                'verbose_name_plural': "Sensor ma'lumotlari",
                'indexes': [models.Index(fields=['plot', 'sensor_type', '-timestamp'], name='irrigation__plot_id_88bf65_idx')],
            },
        ),
    ]
