# Generated by Django 5.1.7 on 2025-04-15 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pump',
            options={'verbose_name': 'Nasos', 'verbose_name_plural': 'Nasoslar'},
        ),
        migrations.RemoveField(
            model_name='field',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='field',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='max_capacity',
        ),
        migrations.AddField(
            model_name='statushistory',
            name='speed',
            field=models.FloatField(default=0.0, help_text='Nasos tezligi litr/sekundda', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Tezlik (l/s)'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='status',
            field=models.CharField(choices=[('yetarli', 'Yetarli'), ('ortacha', "O'rtacha"), ('sugorish_kerak', "Sug'orish kerak")], default='yetarli', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='pump',
            name='last_status_change',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Oxirgi holat o'zgarishi"),
        ),
        migrations.AlterField(
            model_name='pump',
            name='speed',
            field=models.FloatField(default=0.0, help_text='Nasos tezligi foizda', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Tezlik (%)'),
        ),
    ]
